package trashissue.rebage.presentation.theme3

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006d45)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF8ef7c0)
val md_theme_light_onPrimaryContainer = Color(0xFF002112)
val md_theme_light_secondary = Color(0xFF4e6356)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd0e8d7)
val md_theme_light_onSecondaryContainer = Color(0xFF0b1f15)
val md_theme_light_tertiary = Color(0xFF3c6472)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc0e9fa)
val md_theme_light_onTertiaryContainer = Color(0xFF001f29)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf8)
val md_theme_light_onBackground = Color(0xFF191c1a)
val md_theme_light_surface = Color(0xFFfbfdf8)
val md_theme_light_onSurface = Color(0xFF191c1a)
val md_theme_light_surfaceVariant = Color(0xFFdbe5dc)
val md_theme_light_onSurfaceVariant = Color(0xFF404943)
val md_theme_light_outline = Color(0xFF707972)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1ed)
val md_theme_light_inverseSurface = Color(0xFF2d312e)
val md_theme_light_inversePrimary = Color(0xFF72dba6)

val md_theme_dark_primary = Color(0xFF72dba6)
val md_theme_dark_onPrimary = Color(0xFF003822)
val md_theme_dark_primaryContainer = Color(0xFF005233)
val md_theme_dark_onPrimaryContainer = Color(0xFF8ef7c0)
val md_theme_dark_secondary = Color(0xFFb4cdbc)
val md_theme_dark_onSecondary = Color(0xFF203529)
val md_theme_dark_secondaryContainer = Color(0xFF364c3f)
val md_theme_dark_onSecondaryContainer = Color(0xFFd0e8d7)
val md_theme_dark_tertiary = Color(0xFFa4cddd)
val md_theme_dark_onTertiary = Color(0xFF053542)
val md_theme_dark_tertiaryContainer = Color(0xFF234c5a)
val md_theme_dark_onTertiaryContainer = Color(0xFFc0e9fa)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1a)
val md_theme_dark_onBackground = Color(0xFFe1e3df)
val md_theme_dark_surface = Color(0xFF191c1a)
val md_theme_dark_onSurface = Color(0xFFe1e3df)
val md_theme_dark_surfaceVariant = Color(0xFF404943)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c9c1)
val md_theme_dark_outline = Color(0xFF8a938c)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1a)
val md_theme_dark_inverseSurface = Color(0xFFe1e3df)
val md_theme_dark_inversePrimary = Color(0xFF006d45)
